name: build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    name: ðŸ³ dockerize
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ‘‡ Checkout
        uses: actions/checkout@v3

      - name: ðŸ“¦ Setup Docker QEMU
        uses: docker/setup-qemu-action@v2

      - name: ðŸ“¦ Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: ðŸªª Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”ª Git Short Sha
        run: echo "GITHUB_SHA_SHORT=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: ðŸ§± Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.al2
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest,${{ env.REGISTRY }}/${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}
